name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Run tests
        run: just test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
          cache: 'false'

      - name: Set up Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.53'
